In [5]:
import pandas as pd

animals = pd.read_csv("animals_and_carrots.csv", header=None, names=["animal", "carrots_eaten"])
animals

         animal  carrots_eaten
0      Aardvark              1
1     Albatross             88
2     Alligator             35
3        Alpaca             99
4           Ant             69
..          ...            ...
177  Woodpecker              7
178        Worm             42
179        Wren             55
180         Yak             60
181       Zebra              7

[182 rows x 2 columns]

In [10]:
animals["carrots_eaten"] = round(animals["carrots_eaten"], -1) # Rounds to the nearest 10
print("K =", animals.groupby("carrots_eaten").size().min()) # Determine the k factor of the dataset
animals

K = 8

         animal  carrots_eaten
0      Aardvark              0
1     Albatross             90
2     Alligator             40
3        Alpaca            100
4           Ant             70
..          ...            ...
177  Woodpecker             10
178        Worm             40
179        Wren             60
180         Yak             60
181       Zebra             10

[182 rows x 2 columns]